require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GrupoMuscularesController do

  # This should return the minimal set of attributes required to create a valid
  # GrupoMuscular. As you add validations to GrupoMuscular, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GrupoMuscularesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grupo_musculares as @grupo_musculares" do
      grupo_muscular = GrupoMuscular.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grupo_musculares).should eq([grupo_muscular])
    end
  end

  describe "GET show" do
    it "assigns the requested grupo_muscular as @grupo_muscular" do
      grupo_muscular = GrupoMuscular.create! valid_attributes
      get :show, {:id => grupo_muscular.to_param}, valid_session
      assigns(:grupo_muscular).should eq(grupo_muscular)
    end
  end

  describe "GET new" do
    it "assigns a new grupo_muscular as @grupo_muscular" do
      get :new, {}, valid_session
      assigns(:grupo_muscular).should be_a_new(GrupoMuscular)
    end
  end

  describe "GET edit" do
    it "assigns the requested grupo_muscular as @grupo_muscular" do
      grupo_muscular = GrupoMuscular.create! valid_attributes
      get :edit, {:id => grupo_muscular.to_param}, valid_session
      assigns(:grupo_muscular).should eq(grupo_muscular)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GrupoMuscular" do
        expect {
          post :create, {:grupo_muscular => valid_attributes}, valid_session
        }.to change(GrupoMuscular, :count).by(1)
      end

      it "assigns a newly created grupo_muscular as @grupo_muscular" do
        post :create, {:grupo_muscular => valid_attributes}, valid_session
        assigns(:grupo_muscular).should be_a(GrupoMuscular)
        assigns(:grupo_muscular).should be_persisted
      end

      it "redirects to the created grupo_muscular" do
        post :create, {:grupo_muscular => valid_attributes}, valid_session
        response.should redirect_to(GrupoMuscular.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grupo_muscular as @grupo_muscular" do
        # Trigger the behavior that occurs when invalid params are submitted
        GrupoMuscular.any_instance.stub(:save).and_return(false)
        post :create, {:grupo_muscular => {  }}, valid_session
        assigns(:grupo_muscular).should be_a_new(GrupoMuscular)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GrupoMuscular.any_instance.stub(:save).and_return(false)
        post :create, {:grupo_muscular => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grupo_muscular" do
        grupo_muscular = GrupoMuscular.create! valid_attributes
        # Assuming there are no other grupo_musculares in the database, this
        # specifies that the GrupoMuscular created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GrupoMuscular.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => grupo_muscular.to_param, :grupo_muscular => { "these" => "params" }}, valid_session
      end

      it "assigns the requested grupo_muscular as @grupo_muscular" do
        grupo_muscular = GrupoMuscular.create! valid_attributes
        put :update, {:id => grupo_muscular.to_param, :grupo_muscular => valid_attributes}, valid_session
        assigns(:grupo_muscular).should eq(grupo_muscular)
      end

      it "redirects to the grupo_muscular" do
        grupo_muscular = GrupoMuscular.create! valid_attributes
        put :update, {:id => grupo_muscular.to_param, :grupo_muscular => valid_attributes}, valid_session
        response.should redirect_to(grupo_muscular)
      end
    end

    describe "with invalid params" do
      it "assigns the grupo_muscular as @grupo_muscular" do
        grupo_muscular = GrupoMuscular.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GrupoMuscular.any_instance.stub(:save).and_return(false)
        put :update, {:id => grupo_muscular.to_param, :grupo_muscular => {  }}, valid_session
        assigns(:grupo_muscular).should eq(grupo_muscular)
      end

      it "re-renders the 'edit' template" do
        grupo_muscular = GrupoMuscular.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GrupoMuscular.any_instance.stub(:save).and_return(false)
        put :update, {:id => grupo_muscular.to_param, :grupo_muscular => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grupo_muscular" do
      grupo_muscular = GrupoMuscular.create! valid_attributes
      expect {
        delete :destroy, {:id => grupo_muscular.to_param}, valid_session
      }.to change(GrupoMuscular, :count).by(-1)
    end

    it "redirects to the grupo_musculares list" do
      grupo_muscular = GrupoMuscular.create! valid_attributes
      delete :destroy, {:id => grupo_muscular.to_param}, valid_session
      response.should redirect_to(grupo_musculares_url)
    end
  end

end
